### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by vepain** [WaBtey/Huffman#1]
# bug potentiel

Il manque peut être un `/**` à cette ligne :
https://github.com/WaBtey/Huffman/blob/30b0f27c2491c8ea2eb1e83e181b16fa83c5eb46/src/fr/istic/si2/huffman/encodage.scala#L87

```scala
  /** 
   * Le fichier est écrasé s'il était déjà existant.
   *
   * @param nom le nom du fichier dans lequel on écrit
   * @param contenu la chaîne de caractères à écrire
   *
   * @note Le nom de fichier peut être indiqué de manière
   *       relative à la racine du projet courant.
   */
```

**Comment by Wabtey** [comment]
Merci chère confrèro-sulfuro broken <3 
Voici le commit corrigeant l'erreur [050e8664e6f3361c9b4d109e63ec358546f30591](https://github.com/Wabtey/Huffman/commit/050e8664e6f3361c9b4d109e63ec358546f30591)
